services:
  app:
    build: .
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    network_mode: host
    restart: unless-stopped
    healthcheck:
    # ยิงไปเส้น health
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #เช็คทุก 30 วิ
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s